export const ProductService = {
	getData() {
		return [
			{
				Id: '1',
				Branch: 'Karnataka',
				Location: 'Karnataka',
				'Accounting Document No': '9900000573',
				'Document No': 'ST17072217609700',
				'Posting Date': '06-02-2024',
				'Created Date': '06-02-2024 17:46',
				'Created By': 'Salim',
				'Order No': '-',
				'Order Date': '06-02-2024',
				'Party Code': '',
				'Party Name': '',
				'GL Code': '10037',
				'GL Name': 'Finished Goods (FG)',
				'Transaction Type': 'StockPosting',
				'Transaction Activity': 'stockDifferenceMaterialToMaterial',
				Narration: 'Stock Posting - Material To ...',
				'Type(Dr/Cr)': 'DR',
				Amount: '19.6',
				'Clearing Document No': '-',
				'Clearing Document Date': '-',
				'Cleared By': '-',
			},
			{
				Id: '2',
				Branch: 'Karnataka',
				Location: 'Karnataka',
				'Accounting Document No': '9900000573',
				'Document No': 'ST17072217609700',
				'Posting Date': '06-02-2024',
				'Created Date': '06-02-2024 17:46',
				'Created By': 'Salim',
				'Order No': '-',
				'Order Date': '06-02-2024',
				'Party Code': '',
				'Party Name': '',
				'GL Code': '10037',
				'GL Name': 'Finished Goods (FG)',
				'Transaction Type': 'StockPosting',
				'Transaction Activity': 'stockDifferenceMaterialToMaterial',
				Narration: 'Stock Posting - Material To ...',
				'Type(Dr/Cr)': 'CR',
				Amount: '-9.8',
				'Clearing Document No': '-',
				'Clearing Document Date': '-',
				'Cleared By': '-',
			},
			{
				Id: '3',
				Branch: 'Karnataka',
				Location: 'Karnataka',
				'Accounting Document No': '9900000573',
				'Document No': 'ST17072217609700',
				'Posting Date': '06-02-2024',
				'Created Date': '06-02-2024 17:46',
				'Created By': 'Salim',
				'Order No': '-',
				'Order Date': '06-02-2024',
				'Party Code': '',
				'Party Name': '',
				'GL Code': '40037',
				'GL Name': 'Price Difference',
				'Transaction Type': 'StockPosting',
				'Transaction Activity': 'stockDifferenceMaterialToMaterial',
				Narration: 'Stock Posting - Material To ...',
				'Type(Dr/Cr)': 'CR',
				Amount: '-9.8',
				'Clearing Document No': '-',
				'Clearing Document Date': '-',
				'Cleared By': '-',
			},
			{
				Id: '4',
				Branch: 'Karnataka',
				Location: 'Karnataka',
				'Accounting Document No': '9900000572',
				'Document No': 'ST17072201343332',
				'Posting Date': '01-08-2023',
				'Created Date': '06-02-2024 17:18',
				'Created By': 'Sonie Kushwaha',
				'Order No': '-',
				'Order Date': '01-08-2023',
				'Party Code': '',
				'Party Name': '',
				'GL Code': '10037',
				'GL Name': 'Finished Goods (FG)',
				'Transaction Type': 'StockPosting',
				'Transaction Activity': 'stockDifferenceMaterialToMaterial',
				Narration: 'Stock Posting - Material To ...',
				'Type(Dr/Cr)': 'DR',
				Amount: '1285.84',
				'Clearing Document No': '-',
				'Clearing Document Date': '-',
				'Cleared By': '-',
			},
			{
				Id: '5',
				Branch: 'Karnataka',
				Location: 'Karnataka',
				'Accounting Document No': '9900000572',
				'Document No': 'ST17072201343332',
				'Posting Date': '01-08-2023',
				'Created Date': '06-02-2024 17:18',
				'Created By': 'Sonie Kushwaha',
				'Order No': '-',
				'Order Date': '01-08-2023',
				'Party Code': '',
				'Party Name': '',
				'GL Code': '10037',
				'GL Name': 'Finished Goods (FG)',
				'Transaction Type': 'StockPosting',
				'Transaction Activity': 'stockDifferenceMaterialToMaterial',
				Narration: 'Stock Posting - Material To ...',
				'Type(Dr/Cr)': 'CR',
				Amount: '-642.92',
				'Clearing Document No': '-',
				'Clearing Document Date': '-',
				'Cleared By': '-',
			},
			{
				Id: '6',
				Branch: 'Karnataka',
				Location: 'Karnataka',
				'Accounting Document No': '9900000573',
				'Document No': 'ST17072217609700',
				'Posting Date': '06-02-2024',
				'Created Date': '06-02-2024 17:46',
				'Created By': 'Salim',
				'Order No': '-',
				'Order Date': '06-02-2024',
				'Party Code': '',
				'Party Name': '',
				'GL Code': '10037',
				'GL Name': 'Finished Goods (FG)',
				'Transaction Type': 'StockPosting',
				'Transaction Activity': 'stockDifferenceMaterialToMaterial',
				Narration: 'Stock Posting - Material To ...',
				'Type(Dr/Cr)': 'DR',
				Amount: '19.6',
				'Clearing Document No': '-',
				'Clearing Document Date': '-',
				'Cleared By': '-',
			},
			{
				Id: '7',
				Branch: 'Karnataka',
				Location: 'Karnataka',
				'Accounting Document No': '9900000573',
				'Document No': 'ST17072217609700',
				'Posting Date': '06-02-2024',
				'Created Date': '06-02-2024 17:46',
				'Created By': 'Salim',
				'Order No': '-',
				'Order Date': '06-02-2024',
				'Party Code': '',
				'Party Name': '',
				'GL Code': '10037',
				'GL Name': 'Finished Goods (FG)',
				'Transaction Type': 'StockPosting',
				'Transaction Activity': 'stockDifferenceMaterialToMaterial',
				Narration: 'Stock Posting - Material To ...',
				'Type(Dr/Cr)': 'CR',
				Amount: '-9.8',
				'Clearing Document No': '-',
				'Clearing Document Date': '-',
				'Cleared By': '-',
			},
			{
				Id: '8',
				Branch: 'Karnataka',
				Location: 'Karnataka',
				'Accounting Document No': '9900000573',
				'Document No': 'ST17072217609700',
				'Posting Date': '06-02-2024',
				'Created Date': '06-02-2024 17:46',
				'Created By': 'Salim',
				'Order No': '-',
				'Order Date': '06-02-2024',
				'Party Code': '',
				'Party Name': '',
				'GL Code': '40037',
				'GL Name': 'Price Difference',
				'Transaction Type': 'StockPosting',
				'Transaction Activity': 'stockDifferenceMaterialToMaterial',
				Narration: 'Stock Posting - Material To ...',
				'Type(Dr/Cr)': 'CR',
				Amount: '-9.8',
				'Clearing Document No': '-',
				'Clearing Document Date': '-',
				'Cleared By': '-',
			},
			{
				Id: '9',
				Branch: 'Karnataka',
				Location: 'Karnataka',
				'Accounting Document No': '9900000572',
				'Document No': 'ST17072201343332',
				'Posting Date': '01-08-2023',
				'Created Date': '06-02-2024 17:18',
				'Created By': 'Sonie Kushwaha',
				'Order No': '-',
				'Order Date': '01-08-2023',
				'Party Code': '',
				'Party Name': '',
				'GL Code': '10037',
				'GL Name': 'Finished Goods (FG)',
				'Transaction Type': 'StockPosting',
				'Transaction Activity': 'stockDifferenceMaterialToMaterial',
				Narration: 'Stock Posting - Material To ...',
				'Type(Dr/Cr)': 'DR',
				Amount: '1285.84',
				'Clearing Document No': '-',
				'Clearing Document Date': '-',
				'Cleared By': '-',
			},
			{
				Id: '10',
				Branch: 'Karnataka',
				Location: 'Karnataka',
				'Accounting Document No': '9900000572',
				'Document No': 'ST17072201343332',
				'Posting Date': '01-08-2023',
				'Created Date': '06-02-2024 17:18',
				'Created By': 'Sonie Kushwaha',
				'Order No': '-',
				'Order Date': '01-08-2023',
				'Party Code': '',
				'Party Name': '',
				'GL Code': '10037',
				'GL Name': 'Finished Goods (FG)',
				'Transaction Type': 'StockPosting',
				'Transaction Activity': 'stockDifferenceMaterialToMaterial',
				Narration: 'Stock Posting - Material To ...',
				'Type(Dr/Cr)': 'CR',
				Amount: '-642.92',
				'Clearing Document No': '-',
				'Clearing Document Date': '-',
				'Cleared By': '-',
			},
			{
				Id: '11',
				Branch: 'Karnataka',
				Location: 'Karnataka',
				'Accounting Document No': '9900000573',
				'Document No': 'ST17072217609700',
				'Posting Date': '06-02-2024',
				'Created Date': '06-02-2024 17:46',
				'Created By': 'Salim',
				'Order No': '-',
				'Order Date': '06-02-2024',
				'Party Code': '',
				'Party Name': '',
				'GL Code': '10037',
				'GL Name': 'Finished Goods (FG)',
				'Transaction Type': 'StockPosting',
				'Transaction Activity': 'stockDifferenceMaterialToMaterial',
				Narration: 'Stock Posting - Material To ...',
				'Type(Dr/Cr)': 'DR',
				Amount: '19.6',
				'Clearing Document No': '-',
				'Clearing Document Date': '-',
				'Cleared By': '-',
			},
			{
				Id: '12',
				Branch: 'Karnataka',
				Location: 'Karnataka',
				'Accounting Document No': '9900000573',
				'Document No': 'ST17072217609700',
				'Posting Date': '06-02-2024',
				'Created Date': '06-02-2024 17:46',
				'Created By': 'Salim',
				'Order No': '-',
				'Order Date': '06-02-2024',
				'Party Code': '',
				'Party Name': '',
				'GL Code': '10037',
				'GL Name': 'Finished Goods (FG)',
				'Transaction Type': 'StockPosting',
				'Transaction Activity': 'stockDifferenceMaterialToMaterial',
				Narration: 'Stock Posting - Material To ...',
				'Type(Dr/Cr)': 'CR',
				Amount: '-9.8',
				'Clearing Document No': '-',
				'Clearing Document Date': '-',
				'Cleared By': '-',
			},
			{
				Id: '13',
				Branch: 'Karnataka',
				Location: 'Karnataka',
				'Accounting Document No': '9900000573',
				'Document No': 'ST17072217609700',
				'Posting Date': '06-02-2024',
				'Created Date': '06-02-2024 17:46',
				'Created By': 'Salim',
				'Order No': '-',
				'Order Date': '06-02-2024',
				'Party Code': '',
				'Party Name': '',
				'GL Code': '40037',
				'GL Name': 'Price Difference',
				'Transaction Type': 'StockPosting',
				'Transaction Activity': 'stockDifferenceMaterialToMaterial',
				Narration: 'Stock Posting - Material To ...',
				'Type(Dr/Cr)': 'CR',
				Amount: '-9.8',
				'Clearing Document No': '-',
				'Clearing Document Date': '-',
				'Cleared By': '-',
			},
			{
				Id: '14',
				Branch: 'Karnataka',
				Location: 'Karnataka',
				'Accounting Document No': '9900000572',
				'Document No': 'ST17072201343332',
				'Posting Date': '01-08-2023',
				'Created Date': '06-02-2024 17:18',
				'Created By': 'Sonie Kushwaha',
				'Order No': '-',
				'Order Date': '01-08-2023',
				'Party Code': '',
				'Party Name': '',
				'GL Code': '10037',
				'GL Name': 'Finished Goods (FG)',
				'Transaction Type': 'StockPosting',
				'Transaction Activity': 'stockDifferenceMaterialToMaterial',
				Narration: 'Stock Posting - Material To ...',
				'Type(Dr/Cr)': 'DR',
				Amount: '1285.84',
				'Clearing Document No': '-',
				'Clearing Document Date': '-',
				'Cleared By': '-',
			},
			{
				Id: '15',
				Branch: 'Karnataka',
				Location: 'Karnataka',
				'Accounting Document No': '9900000572',
				'Document No': 'ST17072201343332',
				'Posting Date': '01-08-2023',
				'Created Date': '06-02-2024 17:18',
				'Created By': 'Sonie Kushwaha',
				'Order No': '-',
				'Order Date': '01-08-2023',
				'Party Code': '',
				'Party Name': '',
				'GL Code': '10037',
				'GL Name': 'Finished Goods (FG)',
				'Transaction Type': 'StockPosting',
				'Transaction Activity': 'stockDifferenceMaterialToMaterial',
				Narration: 'Stock Posting - Material To ...',
				'Type(Dr/Cr)': 'CR',
				Amount: '-642.92',
				'Clearing Document No': '-',
				'Clearing Document Date': '-',
				'Cleared By': '-',
			},
			{
				Id: '1',
				Branch: 'Karnataka',
				Location: 'Karnataka',
				'Accounting Document No': '9900000573',
				'Document No': 'ST17072217609700',
				'Posting Date': '06-02-2024',
				'Created Date': '06-02-2024 17:46',
				'Created By': 'Salim',
				'Order No': '-',
				'Order Date': '06-02-2024',
				'Party Code': '',
				'Party Name': '',
				'GL Code': '10037',
				'GL Name': 'Finished Goods (FG)',
				'Transaction Type': 'StockPosting',
				'Transaction Activity': 'stockDifferenceMaterialToMaterial',
				Narration: 'Stock Posting - Material To ...',
				'Type(Dr/Cr)': 'DR',
				Amount: '19.6',
				'Clearing Document No': '-',
				'Clearing Document Date': '-',
				'Cleared By': '-',
			},
			{
				Id: '2',
				Branch: 'Karnataka',
				Location: 'Karnataka',
				'Accounting Document No': '9900000573',
				'Document No': 'ST17072217609700',
				'Posting Date': '06-02-2024',
				'Created Date': '06-02-2024 17:46',
				'Created By': 'Salim',
				'Order No': '-',
				'Order Date': '06-02-2024',
				'Party Code': '',
				'Party Name': '',
				'GL Code': '10037',
				'GL Name': 'Finished Goods (FG)',
				'Transaction Type': 'StockPosting',
				'Transaction Activity': 'stockDifferenceMaterialToMaterial',
				Narration: 'Stock Posting - Material To ...',
				'Type(Dr/Cr)': 'CR',
				Amount: '-9.8',
				'Clearing Document No': '-',
				'Clearing Document Date': '-',
				'Cleared By': '-',
			},
			{
				Id: '3',
				Branch: 'Karnataka',
				Location: 'Karnataka',
				'Accounting Document No': '9900000573',
				'Document No': 'ST17072217609700',
				'Posting Date': '06-02-2024',
				'Created Date': '06-02-2024 17:46',
				'Created By': 'Salim',
				'Order No': '-',
				'Order Date': '06-02-2024',
				'Party Code': '',
				'Party Name': '',
				'GL Code': '40037',
				'GL Name': 'Price Difference',
				'Transaction Type': 'StockPosting',
				'Transaction Activity': 'stockDifferenceMaterialToMaterial',
				Narration: 'Stock Posting - Material To ...',
				'Type(Dr/Cr)': 'CR',
				Amount: '-9.8',
				'Clearing Document No': '-',
				'Clearing Document Date': '-',
				'Cleared By': '-',
			},
			{
				Id: '4',
				Branch: 'Karnataka',
				Location: 'Karnataka',
				'Accounting Document No': '9900000572',
				'Document No': 'ST17072201343332',
				'Posting Date': '01-08-2023',
				'Created Date': '06-02-2024 17:18',
				'Created By': 'Sonie Kushwaha',
				'Order No': '-',
				'Order Date': '01-08-2023',
				'Party Code': '',
				'Party Name': '',
				'GL Code': '10037',
				'GL Name': 'Finished Goods (FG)',
				'Transaction Type': 'StockPosting',
				'Transaction Activity': 'stockDifferenceMaterialToMaterial',
				Narration: 'Stock Posting - Material To ...',
				'Type(Dr/Cr)': 'DR',
				Amount: '1285.84',
				'Clearing Document No': '-',
				'Clearing Document Date': '-',
				'Cleared By': '-',
			},
			{
				Id: '5',
				Branch: 'Karnataka',
				Location: 'Karnataka',
				'Accounting Document No': '9900000572',
				'Document No': 'ST17072201343332',
				'Posting Date': '01-08-2023',
				'Created Date': '06-02-2024 17:18',
				'Created By': 'Sonie Kushwaha',
				'Order No': '-',
				'Order Date': '01-08-2023',
				'Party Code': '',
				'Party Name': '',
				'GL Code': '10037',
				'GL Name': 'Finished Goods (FG)',
				'Transaction Type': 'StockPosting',
				'Transaction Activity': 'stockDifferenceMaterialToMaterial',
				Narration: 'Stock Posting - Material To ...',
				'Type(Dr/Cr)': 'CR',
				Amount: '-642.92',
				'Clearing Document No': '-',
				'Clearing Document Date': '-',
				'Cleared By': '-',
			},
			{
				Id: '6',
				Branch: 'Karnataka',
				Location: 'Karnataka',
				'Accounting Document No': '9900000573',
				'Document No': 'ST17072217609700',
				'Posting Date': '06-02-2024',
				'Created Date': '06-02-2024 17:46',
				'Created By': 'Salim',
				'Order No': '-',
				'Order Date': '06-02-2024',
				'Party Code': '',
				'Party Name': '',
				'GL Code': '10037',
				'GL Name': 'Finished Goods (FG)',
				'Transaction Type': 'StockPosting',
				'Transaction Activity': 'stockDifferenceMaterialToMaterial',
				Narration: 'Stock Posting - Material To ...',
				'Type(Dr/Cr)': 'DR',
				Amount: '19.6',
				'Clearing Document No': '-',
				'Clearing Document Date': '-',
				'Cleared By': '-',
			},
			{
				Id: '7',
				Branch: 'Karnataka',
				Location: 'Karnataka',
				'Accounting Document No': '9900000573',
				'Document No': 'ST17072217609700',
				'Posting Date': '06-02-2024',
				'Created Date': '06-02-2024 17:46',
				'Created By': 'Salim',
				'Order No': '-',
				'Order Date': '06-02-2024',
				'Party Code': '',
				'Party Name': '',
				'GL Code': '10037',
				'GL Name': 'Finished Goods (FG)',
				'Transaction Type': 'StockPosting',
				'Transaction Activity': 'stockDifferenceMaterialToMaterial',
				Narration: 'Stock Posting - Material To ...',
				'Type(Dr/Cr)': 'CR',
				Amount: '-9.8',
				'Clearing Document No': '-',
				'Clearing Document Date': '-',
				'Cleared By': '-',
			},
			{
				Id: '8',
				Branch: 'Karnataka',
				Location: 'Karnataka',
				'Accounting Document No': '9900000573',
				'Document No': 'ST17072217609700',
				'Posting Date': '06-02-2024',
				'Created Date': '06-02-2024 17:46',
				'Created By': 'Salim',
				'Order No': '-',
				'Order Date': '06-02-2024',
				'Party Code': '',
				'Party Name': '',
				'GL Code': '40037',
				'GL Name': 'Price Difference',
				'Transaction Type': 'StockPosting',
				'Transaction Activity': 'stockDifferenceMaterialToMaterial',
				Narration: 'Stock Posting - Material To ...',
				'Type(Dr/Cr)': 'CR',
				Amount: '-9.8',
				'Clearing Document No': '-',
				'Clearing Document Date': '-',
				'Cleared By': '-',
			},
			{
				Id: '9',
				Branch: 'Karnataka',
				Location: 'Karnataka',
				'Accounting Document No': '9900000572',
				'Document No': 'ST17072201343332',
				'Posting Date': '01-08-2023',
				'Created Date': '06-02-2024 17:18',
				'Created By': 'Sonie Kushwaha',
				'Order No': '-',
				'Order Date': '01-08-2023',
				'Party Code': '',
				'Party Name': '',
				'GL Code': '10037',
				'GL Name': 'Finished Goods (FG)',
				'Transaction Type': 'StockPosting',
				'Transaction Activity': 'stockDifferenceMaterialToMaterial',
				Narration: 'Stock Posting - Material To ...',
				'Type(Dr/Cr)': 'DR',
				Amount: '1285.84',
				'Clearing Document No': '-',
				'Clearing Document Date': '-',
				'Cleared By': '-',
			},
			{
				Id: '10',
				Branch: 'Karnataka',
				Location: 'Karnataka',
				'Accounting Document No': '9900000572',
				'Document No': 'ST17072201343332',
				'Posting Date': '01-08-2023',
				'Created Date': '06-02-2024 17:18',
				'Created By': 'Sonie Kushwaha',
				'Order No': '-',
				'Order Date': '01-08-2023',
				'Party Code': '',
				'Party Name': '',
				'GL Code': '10037',
				'GL Name': 'Finished Goods (FG)',
				'Transaction Type': 'StockPosting',
				'Transaction Activity': 'stockDifferenceMaterialToMaterial',
				Narration: 'Stock Posting - Material To ...',
				'Type(Dr/Cr)': 'CR',
				Amount: '-642.92',
				'Clearing Document No': '-',
				'Clearing Document Date': '-',
				'Cleared By': '-',
			},
			{
				Id: '11',
				Branch: 'Karnataka',
				Location: 'Karnataka',
				'Accounting Document No': '9900000573',
				'Document No': 'ST17072217609700',
				'Posting Date': '06-02-2024',
				'Created Date': '06-02-2024 17:46',
				'Created By': 'Salim',
				'Order No': '-',
				'Order Date': '06-02-2024',
				'Party Code': '',
				'Party Name': '',
				'GL Code': '10037',
				'GL Name': 'Finished Goods (FG)',
				'Transaction Type': 'StockPosting',
				'Transaction Activity': 'stockDifferenceMaterialToMaterial',
				Narration: 'Stock Posting - Material To ...',
				'Type(Dr/Cr)': 'DR',
				Amount: '19.6',
				'Clearing Document No': '-',
				'Clearing Document Date': '-',
				'Cleared By': '-',
			},
			{
				Id: '12',
				Branch: 'Karnataka',
				Location: 'Karnataka',
				'Accounting Document No': '9900000573',
				'Document No': 'ST17072217609700',
				'Posting Date': '06-02-2024',
				'Created Date': '06-02-2024 17:46',
				'Created By': 'Salim',
				'Order No': '-',
				'Order Date': '06-02-2024',
				'Party Code': '',
				'Party Name': '',
				'GL Code': '10037',
				'GL Name': 'Finished Goods (FG)',
				'Transaction Type': 'StockPosting',
				'Transaction Activity': 'stockDifferenceMaterialToMaterial',
				Narration: 'Stock Posting - Material To ...',
				'Type(Dr/Cr)': 'CR',
				Amount: '-9.8',
				'Clearing Document No': '-',
				'Clearing Document Date': '-',
				'Cleared By': '-',
			},
			{
				Id: '13',
				Branch: 'Karnataka',
				Location: 'Karnataka',
				'Accounting Document No': '9900000573',
				'Document No': 'ST17072217609700',
				'Posting Date': '06-02-2024',
				'Created Date': '06-02-2024 17:46',
				'Created By': 'Salim',
				'Order No': '-',
				'Order Date': '06-02-2024',
				'Party Code': '',
				'Party Name': '',
				'GL Code': '40037',
				'GL Name': 'Price Difference',
				'Transaction Type': 'StockPosting',
				'Transaction Activity': 'stockDifferenceMaterialToMaterial',
				Narration: 'Stock Posting - Material To ...',
				'Type(Dr/Cr)': 'CR',
				Amount: '-9.8',
				'Clearing Document No': '-',
				'Clearing Document Date': '-',
				'Cleared By': '-',
			},
			{
				Id: '14',
				Branch: 'Karnataka',
				Location: 'Karnataka',
				'Accounting Document No': '9900000572',
				'Document No': 'ST17072201343332',
				'Posting Date': '01-08-2023',
				'Created Date': '06-02-2024 17:18',
				'Created By': 'Sonie Kushwaha',
				'Order No': '-',
				'Order Date': '01-08-2023',
				'Party Code': '',
				'Party Name': '',
				'GL Code': '10037',
				'GL Name': 'Finished Goods (FG)',
				'Transaction Type': 'StockPosting',
				'Transaction Activity': 'stockDifferenceMaterialToMaterial',
				Narration: 'Stock Posting - Material To ...',
				'Type(Dr/Cr)': 'DR',
				Amount: '1285.84',
				'Clearing Document No': '-',
				'Clearing Document Date': '-',
				'Cleared By': '-',
			},
			{
				Id: '15',
				Branch: 'Karnataka',
				Location: 'Karnataka',
				'Accounting Document No': '9900000572',
				'Document No': 'ST17072201343332',
				'Posting Date': '01-08-2023',
				'Created Date': '06-02-2024 17:18',
				'Created By': 'Sonie Kushwaha',
				'Order No': '-',
				'Order Date': '01-08-2023',
				'Party Code': '',
				'Party Name': '',
				'GL Code': '10037',
				'GL Name': 'Finished Goods (FG)',
				'Transaction Type': 'StockPosting',
				'Transaction Activity': 'stockDifferenceMaterialToMaterial',
				Narration: 'Stock Posting - Material To ...',
				'Type(Dr/Cr)': 'CR',
				Amount: '-642.92',
				'Clearing Document No': '-',
				'Clearing Document Date': '-',
				'Cleared By': '-',
			},
			{
				Id: '1',
				Branch: 'Karnataka',
				Location: 'Karnataka',
				'Accounting Document No': '9900000573',
				'Document No': 'ST17072217609700',
				'Posting Date': '06-02-2024',
				'Created Date': '06-02-2024 17:46',
				'Created By': 'Salim',
				'Order No': '-',
				'Order Date': '06-02-2024',
				'Party Code': '',
				'Party Name': '',
				'GL Code': '10037',
				'GL Name': 'Finished Goods (FG)',
				'Transaction Type': 'StockPosting',
				'Transaction Activity': 'stockDifferenceMaterialToMaterial',
				Narration: 'Stock Posting - Material To ...',
				'Type(Dr/Cr)': 'DR',
				Amount: '19.6',
				'Clearing Document No': '-',
				'Clearing Document Date': '-',
				'Cleared By': '-',
			},
			{
				Id: '2',
				Branch: 'Karnataka',
				Location: 'Karnataka',
				'Accounting Document No': '9900000573',
				'Document No': 'ST17072217609700',
				'Posting Date': '06-02-2024',
				'Created Date': '06-02-2024 17:46',
				'Created By': 'Salim',
				'Order No': '-',
				'Order Date': '06-02-2024',
				'Party Code': '',
				'Party Name': '',
				'GL Code': '10037',
				'GL Name': 'Finished Goods (FG)',
				'Transaction Type': 'StockPosting',
				'Transaction Activity': 'stockDifferenceMaterialToMaterial',
				Narration: 'Stock Posting - Material To ...',
				'Type(Dr/Cr)': 'CR',
				Amount: '-9.8',
				'Clearing Document No': '-',
				'Clearing Document Date': '-',
				'Cleared By': '-',
			},
			{
				Id: '3',
				Branch: 'Karnataka',
				Location: 'Karnataka',
				'Accounting Document No': '9900000573',
				'Document No': 'ST17072217609700',
				'Posting Date': '06-02-2024',
				'Created Date': '06-02-2024 17:46',
				'Created By': 'Salim',
				'Order No': '-',
				'Order Date': '06-02-2024',
				'Party Code': '',
				'Party Name': '',
				'GL Code': '40037',
				'GL Name': 'Price Difference',
				'Transaction Type': 'StockPosting',
				'Transaction Activity': 'stockDifferenceMaterialToMaterial',
				Narration: 'Stock Posting - Material To ...',
				'Type(Dr/Cr)': 'CR',
				Amount: '-9.8',
				'Clearing Document No': '-',
				'Clearing Document Date': '-',
				'Cleared By': '-',
			},
			{
				Id: '4',
				Branch: 'Karnataka',
				Location: 'Karnataka',
				'Accounting Document No': '9900000572',
				'Document No': 'ST17072201343332',
				'Posting Date': '01-08-2023',
				'Created Date': '06-02-2024 17:18',
				'Created By': 'Sonie Kushwaha',
				'Order No': '-',
				'Order Date': '01-08-2023',
				'Party Code': '',
				'Party Name': '',
				'GL Code': '10037',
				'GL Name': 'Finished Goods (FG)',
				'Transaction Type': 'StockPosting',
				'Transaction Activity': 'stockDifferenceMaterialToMaterial',
				Narration: 'Stock Posting - Material To ...',
				'Type(Dr/Cr)': 'DR',
				Amount: '1285.84',
				'Clearing Document No': '-',
				'Clearing Document Date': '-',
				'Cleared By': '-',
			},
			{
				Id: '5',
				Branch: 'Karnataka',
				Location: 'Karnataka',
				'Accounting Document No': '9900000572',
				'Document No': 'ST17072201343332',
				'Posting Date': '01-08-2023',
				'Created Date': '06-02-2024 17:18',
				'Created By': 'Sonie Kushwaha',
				'Order No': '-',
				'Order Date': '01-08-2023',
				'Party Code': '',
				'Party Name': '',
				'GL Code': '10037',
				'GL Name': 'Finished Goods (FG)',
				'Transaction Type': 'StockPosting',
				'Transaction Activity': 'stockDifferenceMaterialToMaterial',
				Narration: 'Stock Posting - Material To ...',
				'Type(Dr/Cr)': 'CR',
				Amount: '-642.92',
				'Clearing Document No': '-',
				'Clearing Document Date': '-',
				'Cleared By': '-',
			},
			{
				Id: '6',
				Branch: 'Karnataka',
				Location: 'Karnataka',
				'Accounting Document No': '9900000573',
				'Document No': 'ST17072217609700',
				'Posting Date': '06-02-2024',
				'Created Date': '06-02-2024 17:46',
				'Created By': 'Salim',
				'Order No': '-',
				'Order Date': '06-02-2024',
				'Party Code': '',
				'Party Name': '',
				'GL Code': '10037',
				'GL Name': 'Finished Goods (FG)',
				'Transaction Type': 'StockPosting',
				'Transaction Activity': 'stockDifferenceMaterialToMaterial',
				Narration: 'Stock Posting - Material To ...',
				'Type(Dr/Cr)': 'DR',
				Amount: '19.6',
				'Clearing Document No': '-',
				'Clearing Document Date': '-',
				'Cleared By': '-',
			},
			{
				Id: '7',
				Branch: 'Karnataka',
				Location: 'Karnataka',
				'Accounting Document No': '9900000573',
				'Document No': 'ST17072217609700',
				'Posting Date': '06-02-2024',
				'Created Date': '06-02-2024 17:46',
				'Created By': 'Salim',
				'Order No': '-',
				'Order Date': '06-02-2024',
				'Party Code': '',
				'Party Name': '',
				'GL Code': '10037',
				'GL Name': 'Finished Goods (FG)',
				'Transaction Type': 'StockPosting',
				'Transaction Activity': 'stockDifferenceMaterialToMaterial',
				Narration: 'Stock Posting - Material To ...',
				'Type(Dr/Cr)': 'CR',
				Amount: '-9.8',
				'Clearing Document No': '-',
				'Clearing Document Date': '-',
				'Cleared By': '-',
			},
			{
				Id: '8',
				Branch: 'Karnataka',
				Location: 'Karnataka',
				'Accounting Document No': '9900000573',
				'Document No': 'ST17072217609700',
				'Posting Date': '06-02-2024',
				'Created Date': '06-02-2024 17:46',
				'Created By': 'Salim',
				'Order No': '-',
				'Order Date': '06-02-2024',
				'Party Code': '',
				'Party Name': '',
				'GL Code': '40037',
				'GL Name': 'Price Difference',
				'Transaction Type': 'StockPosting',
				'Transaction Activity': 'stockDifferenceMaterialToMaterial',
				Narration: 'Stock Posting - Material To ...',
				'Type(Dr/Cr)': 'CR',
				Amount: '-9.8',
				'Clearing Document No': '-',
				'Clearing Document Date': '-',
				'Cleared By': '-',
			},
			{
				Id: '9',
				Branch: 'Karnataka',
				Location: 'Karnataka',
				'Accounting Document No': '9900000572',
				'Document No': 'ST17072201343332',
				'Posting Date': '01-08-2023',
				'Created Date': '06-02-2024 17:18',
				'Created By': 'Sonie Kushwaha',
				'Order No': '-',
				'Order Date': '01-08-2023',
				'Party Code': '',
				'Party Name': '',
				'GL Code': '10037',
				'GL Name': 'Finished Goods (FG)',
				'Transaction Type': 'StockPosting',
				'Transaction Activity': 'stockDifferenceMaterialToMaterial',
				Narration: 'Stock Posting - Material To ...',
				'Type(Dr/Cr)': 'DR',
				Amount: '1285.84',
				'Clearing Document No': '-',
				'Clearing Document Date': '-',
				'Cleared By': '-',
			},
			{
				Id: '10',
				Branch: 'Karnataka',
				Location: 'Karnataka',
				'Accounting Document No': '9900000572',
				'Document No': 'ST17072201343332',
				'Posting Date': '01-08-2023',
				'Created Date': '06-02-2024 17:18',
				'Created By': 'Sonie Kushwaha',
				'Order No': '-',
				'Order Date': '01-08-2023',
				'Party Code': '',
				'Party Name': '',
				'GL Code': '10037',
				'GL Name': 'Finished Goods (FG)',
				'Transaction Type': 'StockPosting',
				'Transaction Activity': 'stockDifferenceMaterialToMaterial',
				Narration: 'Stock Posting - Material To ...',
				'Type(Dr/Cr)': 'CR',
				Amount: '-642.92',
				'Clearing Document No': '-',
				'Clearing Document Date': '-',
				'Cleared By': '-',
			},
			{
				Id: '11',
				Branch: 'Karnataka',
				Location: 'Karnataka',
				'Accounting Document No': '9900000573',
				'Document No': 'ST17072217609700',
				'Posting Date': '06-02-2024',
				'Created Date': '06-02-2024 17:46',
				'Created By': 'Salim',
				'Order No': '-',
				'Order Date': '06-02-2024',
				'Party Code': '',
				'Party Name': '',
				'GL Code': '10037',
				'GL Name': 'Finished Goods (FG)',
				'Transaction Type': 'StockPosting',
				'Transaction Activity': 'stockDifferenceMaterialToMaterial',
				Narration: 'Stock Posting - Material To ...',
				'Type(Dr/Cr)': 'DR',
				Amount: '19.6',
				'Clearing Document No': '-',
				'Clearing Document Date': '-',
				'Cleared By': '-',
			},
			{
				Id: '12',
				Branch: 'Karnataka',
				Location: 'Karnataka',
				'Accounting Document No': '9900000573',
				'Document No': 'ST17072217609700',
				'Posting Date': '06-02-2024',
				'Created Date': '06-02-2024 17:46',
				'Created By': 'Salim',
				'Order No': '-',
				'Order Date': '06-02-2024',
				'Party Code': '',
				'Party Name': '',
				'GL Code': '10037',
				'GL Name': 'Finished Goods (FG)',
				'Transaction Type': 'StockPosting',
				'Transaction Activity': 'stockDifferenceMaterialToMaterial',
				Narration: 'Stock Posting - Material To ...',
				'Type(Dr/Cr)': 'CR',
				Amount: '-9.8',
				'Clearing Document No': '-',
				'Clearing Document Date': '-',
				'Cleared By': '-',
			},
			{
				Id: '13',
				Branch: 'Karnataka',
				Location: 'Karnataka',
				'Accounting Document No': '9900000573',
				'Document No': 'ST17072217609700',
				'Posting Date': '06-02-2024',
				'Created Date': '06-02-2024 17:46',
				'Created By': 'Salim',
				'Order No': '-',
				'Order Date': '06-02-2024',
				'Party Code': '',
				'Party Name': '',
				'GL Code': '40037',
				'GL Name': 'Price Difference',
				'Transaction Type': 'StockPosting',
				'Transaction Activity': 'stockDifferenceMaterialToMaterial',
				Narration: 'Stock Posting - Material To ...',
				'Type(Dr/Cr)': 'CR',
				Amount: '-9.8',
				'Clearing Document No': '-',
				'Clearing Document Date': '-',
				'Cleared By': '-',
			},
			{
				Id: '14',
				Branch: 'Karnataka',
				Location: 'Karnataka',
				'Accounting Document No': '9900000572',
				'Document No': 'ST17072201343332',
				'Posting Date': '01-08-2023',
				'Created Date': '06-02-2024 17:18',
				'Created By': 'Sonie Kushwaha',
				'Order No': '-',
				'Order Date': '01-08-2023',
				'Party Code': '',
				'Party Name': '',
				'GL Code': '10037',
				'GL Name': 'Finished Goods (FG)',
				'Transaction Type': 'StockPosting',
				'Transaction Activity': 'stockDifferenceMaterialToMaterial',
				Narration: 'Stock Posting - Material To ...',
				'Type(Dr/Cr)': 'DR',
				Amount: '1285.84',
				'Clearing Document No': '-',
				'Clearing Document Date': '-',
				'Cleared By': '-',
			},
			{
				Id: '15',
				Branch: 'Karnataka',
				Location: 'Karnataka',
				'Accounting Document No': '9900000572',
				'Document No': 'ST17072201343332',
				'Posting Date': '01-08-2023',
				'Created Date': '06-02-2024 17:18',
				'Created By': 'Sonie Kushwaha',
				'Order No': '-',
				'Order Date': '01-08-2023',
				'Party Code': '',
				'Party Name': '',
				'GL Code': '10037',
				'GL Name': 'Finished Goods (FG)',
				'Transaction Type': 'StockPosting',
				'Transaction Activity': 'stockDifferenceMaterialToMaterial',
				Narration: 'Stock Posting - Material To ...',
				'Type(Dr/Cr)': 'CR',
				Amount: '-642.92',
				'Clearing Document No': '-',
				'Clearing Document Date': '-',
				'Cleared By': '-',
			},
		];
	},

	getProductsSmall() {
		return Promise.resolve(this.getData().slice(0, 10));
	},

	getProductsMedium() {
		return Promise.resolve(this.getData().slice(0, 50));
	},

	getProductsLarge() {
		return Promise.resolve(this.getData().slice(0, 200));
	},

	getProductsXLarge() {
		return Promise.resolve(this.getData());
	},
};
